### ISSUE TITLE
Unit Tests failing, dependency error!

### ISSUE THREAD

**Issue by ravisaluru** [ravisaluru/software_testing_project#1]
Need to search for the dependent files. Maybe from the maven respository

Error ->
java.lang.RuntimeException: Class mocking requires to have cglib and objenesis librairies in the classpath
	at org.easymock.internal.MocksControl.getClassProxyFactory(MocksControl.java:164)

**Comment by sandeesaripalli** [comment]
Downloaded the dependent files from maven.org. Need to add the files as external reference jar libraries.
1. cglib
2. objenesis
3. JUnit jar
4. Mocking 3+ version jar

Needs to be added whenever we checkout from the github.
